server:
  port: 8883
  servlet:
    session:
      timeout: 90m

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DEVBLOG3
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

imc:
  mt:
    sms: sms-property-local
    lms: lms-property-local
    mms: mms-property-local
  ft: friendtalk-local
  at: alimtalk-local