server:
  port: 8883

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DEVBLOG3
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # 주의!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: false

logging:
  level:
    root: INFO