server:
  port: 8883
  servlet:
    session:
      timeout: 90m

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DEVBLOG3
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

imc:
  mt:
    sms: sms-property-dev
    lms: lms-property-dev
    mms: mms-property-dev
  ft: friendtalk-dev
  at: alimtalk-dev